DROP SCHEMA IF EXISTS remedios_db;
CREATE SCHEMA remedios_db;
USE remedios_db;

-- CREATE USER 'appuser'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'appuser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE USUARIOS 
( 
 ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(150) NOT NULL,
 SENHA VARCHAR(255) NOT NULL,  
 TIPO VARCHAR(20) NOT NULL
); 

CREATE TABLE PRESCRICOES
(
 ID_PRESCRICAO INT PRIMARY KEY AUTO_INCREMENT,
 PUBLICO_ALVO VARCHAR(200) NOT NULL,  
 PRECAUCOES VARCHAR(200) NOT NULL,  
 CONTRA_INDICACOES VARCHAR(200) NOT NULL,  
 COMPOSICAO VARCHAR(200),  
 EFEITOS VARCHAR(200) NOT NULL 
);
CREATE TABLE SUBSTANCIAS
(
 ID_SUBSTANCIA INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(200) NOT NULL,
 TIPO VARCHAR(100) NOT NULL
 );

CREATE TABLE REMEDIOS 
( 
 ID_REMEDIO INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(100) NOT NULL,
 BULA VARCHAR(255) NOT NULL, -- a bula será uma URL, porque BLOB fica muito pesado
 TIPO CHAR NOT NULL,
 ID_USUARIO INT,
 ID_PRESCRICAO INT,
 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE SET NULL,
 FOREIGN KEY (ID_PRESCRICAO) REFERENCES PRESCRICOES(ID_PRESCRICAO)
); 

CREATE TABLE SUBSTANCIAS_REMEDIOS
(
 ID_SUBSTANCIAS_REMEDIOS INT AUTO_INCREMENT PRIMARY KEY,
 ID_SUBSTANCIA INT,
 ID_REMEDIO INT,

 FOREIGN KEY (ID_SUBSTANCIA) REFERENCES SUBSTANCIAS(ID_SUBSTANCIA),
 FOREIGN KEY (ID_REMEDIO) REFERENCES REMEDIOS(ID_REMEDIO)
);

CREATE TABLE CIDADES
(
 ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(200) NOT NULL,
 UF CHAR(2)
);

CREATE TABLE EMPRESAS 
( 
 ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(100) NOT NULL,  
 CNPJ CHAR(14) NOT NULL,
 ID_CIDADE INT,
 FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID_CIDADE)
); 

CREATE TABLE EMPRESAS_REMEDIOS
( 
 ID_EMPRESA_REMEDIO INT AUTO_INCREMENT,
 ID_EMPRESA INT,  
 ID_REMEDIO INT,  
 UNIQUE (ID_EMPRESA, ID_REMEDIO),
 PRIMARY KEY (ID_EMPRESA_REMEDIO),
 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
 FOREIGN KEY (ID_REMEDIO) REFERENCES REMEDIOS(ID_REMEDIO)
); 

SELECT * FROM REMEDIOS R, PRESCRICOES P WHERE R.ID_PRESCRICAO = P.ID_PRESCRICAO;
SELECT * FROM USUARIOS;
SELECT * FROM EMPRESAS;
INSERT INTO USUARIOS VALUES (2,"brasil@e.com", "brasil", "professor")
