DROP SCHEMA IF EXISTS remedios_db;
CREATE SCHEMA remedios_db
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;	
USE remedios_db;

-- CREATE USER 'appuser'@'localhost' IDENTIFIED BY '1234';
-- GRANT SELECT, INSERT, UPDATE, DELETE
-- ON remedios_db.*
-- TO 'appuser'@'%';

DROP SCHEMA IF EXISTS remedios_db;
CREATE SCHEMA remedios_db;
USE remedios_db;

CREATE TABLE USUARIOS
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE PRESCRICOES
(
    ID_PRESCRICAO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    RESTRICAO VARCHAR(250) NOT NULL,
    CONTRA_INDICACOES VARCHAR(2000) NOT NULL,
    EFEITOS VARCHAR(1000) NOT NULL,
    VALIDADE VARCHAR(250) NOT NULL,
    CONSERVACAO VARCHAR(100) NOT NULL
);

CREATE TABLE SUBSTANCIAS
(
    ID_SUBSTANCIA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE PUBLICO_ALVO
(
    ID_PUBLICO_ALVO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE TARJAS
(
    ID_TARJA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE CIDADES
(
    ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    UF CHAR(2)
);

CREATE TABLE EMPRESAS
(
    ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CNPJ CHAR(14),
    ID_CIDADE INT,

    FOREIGN KEY (ID_CIDADE)
    REFERENCES CIDADES(ID_CIDADE)
    ON DELETE SET NULL
);

	CREATE TABLE REMEDIOS
	(
		ID_REMEDIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
		NOME VARCHAR(100) NOT NULL,
		BULA VARCHAR(255) NOT NULL,
		TIPO VARCHAR(20) NOT NULL,

		ID_USUARIO INT,
		ID_PRESCRICAO INT NOT NULL,
		ID_TARJA INT,
        ID_SUBSTANCIA INT NOT NULL,
        ID_EMPRESA INT,

		FOREIGN KEY (ID_USUARIO)
		REFERENCES USUARIOS(ID_USUARIO)
		ON DELETE SET NULL,

		FOREIGN KEY (ID_PRESCRICAO)
		REFERENCES PRESCRICOES(ID_PRESCRICAO)
		ON DELETE CASCADE,

		FOREIGN KEY (ID_TARJA)
		REFERENCES TARJAS(ID_TARJA)
		ON DELETE SET NULL,
		
		FOREIGN KEY (ID_SUBSTANCIA)
		REFERENCES SUBSTANCIAS(ID_SUBSTANCIA)
		ON DELETE CASCADE,
        
        FOREIGN KEY (ID_EMPRESA)
		REFERENCES EMPRESAS(ID_EMPRESA)
		ON DELETE SET NULL
	);

CREATE TABLE REMEDIOS_PUBLICO_ALVO
(
    ID_REMEDIO_PUBLICO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,

    ID_REMEDIO INT NOT NULL,
    ID_PUBLICO_ALVO INT NOT NULL,

    UNIQUE (ID_REMEDIO, ID_PUBLICO_ALVO),

    FOREIGN KEY (ID_REMEDIO)
    REFERENCES REMEDIOS(ID_REMEDIO)
    ON DELETE CASCADE,

    FOREIGN KEY (ID_PUBLICO_ALVO)
    REFERENCES PUBLICO_ALVO(ID_PUBLICO_ALVO)
    ON DELETE CASCADE
);

INSERT INTO TARJAS (NOME) VALUES
('Sem tarja'),
('Vermelha'),
('Preta');

INSERT INTO PUBLICO_ALVO (NOME) VALUES
('Crianças'),
('Adultos'),
('Idosos'),
('Gestantes');

INSERT INTO CIDADES (NOME, UF) VALUES
('Londrina', 'PR'), ('São Paulo', 'SP'), ('Curitiba', 'PR'), ('Maringá', 'PR'), ('Cascavel', 'PR'), ('Foz do Iguaçu', 'PR'),
('Porto Alegre', 'RS'),
('Florianópolis', 'SC'),
('Belo Horizonte', 'MG'),
('Rio de Janeiro', 'RJ'),
('Campinas', 'SP'),
('Ribeirão Preto', 'SP'),
('Salvador', 'BA'),
('Recife', 'PE'),
('Brasília', 'DF'),
('Buenos Aires', NULL),
('Montevidéu', NULL),
('Santiago', NULL),
('Assunção', NULL),
('Lisboa', NULL),
('Madrid', NULL),
('Nova York', NULL),
('Tóquio', NULL);

INSERT INTO EMPRESAS (NOME, CNPJ, ID_CIDADE) VALUES
('EMS', '11111111111111', 2),
('Medley', '22222222222222', 2),
('Eurofarma', '33333333333333', 2),
('Neo Química', '44444444444444', 2),
('Aché', '55555555555555', 2),
('Cimed', '66666666666666', 8),
('União Química', '77777777777777', 9),
('Cristália', '88888888888888', 11),
('Biolab', '99999999999999', 2),
('Libbs', '10101010101010', 2),
('Prati-Donaduzzi', '12121212121212', 5),
('Farmácias Nissei', '13131313131313', 1),
('Herbarium', '14141414141414', 3),
('Sanofi Brasil', '15151515151515', 2),
('Pfizer Brasil', '16161616161616', 2),
('Bayer Brasil', '17171717171717', 2),
('Novartis Brasil', '18181818181818', 2),
('Roche Brasil', '19191919191919', 2),
('Merck', '20202020202020', 20),
('Takeda', '21212121212121', 22);

SELECT R.*, P.*, T.NOME AS TARJA, PA.NOME AS PUBLICO_ALVO_NOME, E.NOME AS EMPRESA, E.CNPJ, C.NOME AS CIDADE, C.UF, S.NOME AS SUBSTANCIA, S.TIPO AS SUBSTANCIA_TIPO FROM REMEDIOS R, PRESCRICOES P, TARJAS T, REMEDIOS_PUBLICO_ALVO RPA, PUBLICO_ALVO PA, EMPRESAS E, CIDADES C, SUBSTANCIAS S WHERE R.ID_PRESCRICAO = P.ID_PRESCRICAO AND R.ID_TARJA = T.ID_TARJA AND R.ID_REMEDIO = RPA.ID_REMEDIO AND RPA.ID_PUBLICO_ALVO = PA.ID_PUBLICO_ALVO AND R.ID_EMPRESA = E.ID_EMPRESA AND E.ID_CIDADE = C.ID_CIDADE AND R.ID_SUBSTANCIA = S.ID_SUBSTANCIA;
-- SELECT * FROM USUARIOS;
SELECT * FROM EMPRESAS;