DROP SCHEMA IF EXISTS remedios_db;
CREATE SCHEMA remedios_db;
USE remedios_db;

-- CREATE USER 'appuser'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'appuser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE USUARIOS
(
 ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(150) NOT NULL,
 SENHA VARCHAR(255) NOT NULL,  
 TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE PRESCRICOES
(
 ID_PRESCRICAO INT PRIMARY KEY AUTO_INCREMENT,
 RESTRICAO VARCHAR(250) NOT NULL,  
 CONTRA_INDICACOES VARCHAR(250) NOT NULL,  
 COMPOSICAO VARCHAR(200) NOT NULL,  
 EFEITOS VARCHAR(250) NOT NULL,
 VALIDADE VARCHAR(250) NOT NULL
);
CREATE TABLE SUBSTANCIAS
(
 ID_SUBSTANCIA INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(200) NOT NULL,
 TIPO VARCHAR(100) NOT NULL
 );
 
 CREATE TABLE PUBLICO_ALVO (
    ID_PUBLICO_ALVO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE TARJAS (
    ID_TARJA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL
);
CREATE TABLE REMEDIOS
(
 ID_REMEDIO INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(100) NOT NULL,
 BULA VARCHAR(255) NOT NULL, -- a bula será uma URL, porque BLOB fica muito pesado
 TIPO VARCHAR(20) NOT NULL,
 ID_USUARIO INT,
 ID_PRESCRICAO INT,
 ID_TARJA INT,
 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE SET NULL,
 FOREIGN KEY (ID_PRESCRICAO) REFERENCES PRESCRICOES(ID_PRESCRICAO),
 FOREIGN KEY (ID_TARJA) REFERENCES TARJAS(ID_TARJA)
);

CREATE TABLE SUBSTANCIAS_REMEDIOS
(
 ID_SUBSTANCIAS_REMEDIOS INT AUTO_INCREMENT PRIMARY KEY,
 ID_SUBSTANCIA INT NOT NULL,
 ID_REMEDIO INT NOT NULL,

 FOREIGN KEY (ID_SUBSTANCIA) REFERENCES SUBSTANCIAS(ID_SUBSTANCIA),
 FOREIGN KEY (ID_REMEDIO) REFERENCES REMEDIOS(ID_REMEDIO)
);

CREATE TABLE REMEDIOS_PUBLICO_ALVO (
    ID_REMEDIO_PUBLICO INT PRIMARY KEY AUTO_INCREMENT,
    ID_REMEDIO INT NOT NULL,
    ID_PUBLICO_ALVO INT NOT NULL,
    FOREIGN KEY (ID_REMEDIO) REFERENCES REMEDIOS(ID_REMEDIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PUBLICO_ALVO) REFERENCES PUBLICO_ALVO(ID_PUBLICO_ALVO) ON DELETE CASCADE,
    UNIQUE (ID_REMEDIO, ID_PUBLICO_ALVO)
);

CREATE TABLE CIDADES
(
 ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(200) NOT NULL,
 UF CHAR(2)
);

CREATE TABLE EMPRESAS
(
 ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(100) NOT NULL,  
 CNPJ CHAR(14), -- UNIQUE,
 ID_CIDADE INT,
 FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID_CIDADE)
);

CREATE TABLE EMPRESAS_REMEDIOS
(
 ID_EMPRESA_REMEDIO INT AUTO_INCREMENT,
 ID_EMPRESA INT,  
 ID_REMEDIO INT,  
 UNIQUE (ID_EMPRESA, ID_REMEDIO),
 PRIMARY KEY (ID_EMPRESA_REMEDIO),
 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
 FOREIGN KEY (ID_REMEDIO) REFERENCES REMEDIOS(ID_REMEDIO)
);

INSERT INTO TARJAS (NOME) VALUES
('Sem tarja'),
('Vermelha'),
('Preta');

INSERT INTO PUBLICO_ALVO (NOME) VALUES
('Crianças'),
('Adultos'),
('Idosos'),
('Gestantes');


SELECT R.*,P.*,E.NOME EMPRESA, E.CNPJ, C.NOME CIDADE, C.UF, S.NOME SUBSTANCIA, S.TIPO SUBSTANCIA_TIPO FROM REMEDIOS R, PRESCRICOES P,EMPRESAS_REMEDIOS ER,EMPRESAS E,CIDADES C,SUBSTANCIAS_REMEDIOS SR,SUBSTANCIAS S WHERE R.ID_PRESCRICAO = P.ID_PRESCRICAO AND R.ID_REMEDIO = ER.ID_REMEDIO AND ER.ID_EMPRESA = E.ID_EMPRESA AND E.ID_CIDADE = C.ID_CIDADE AND R.ID_REMEDIO = SR.ID_REMEDIO AND SR.ID_SUBSTANCIA = S.ID_SUBSTANCIA;
SELECT * FROM USUARIOS;
SELECT * FROM EMPRESAS;
INSERT INTO USUARIOS VALUES (2,"brasil@e.com", "brasil", "professor")