DROP SCHEMA IF EXISTS remedios_db;
CREATE SCHEMA remedios_db;
USE remedios_db;

CREATE TABLE USUARIOS 
( 
 ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,  
 SENHA VARCHAR(255) NOT NULL,  
 TIPO VARCHAR(20) NOT NULL,  
 NOME VARCHAR(100) NOT NULL
); 

CREATE TABLE REMEDIOS 
( 
 ID_REMEDIO INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(100) NOT NULL,  
 BULA VARCHAR(255) NOT NULL, -- a bula será uma URL, porque BLOB fica muito pesado  
 ID_USUARIOS INT,
 PUBLICO_ALVO VARCHAR(200) NOT NULL,  
 PRECAUCOES VARCHAR(200) NOT NULL,  
 CONTRA_INDICACOES VARCHAR(200) NOT NULL,  
 COMPOSICAO VARCHAR(200),  
 EFEITOS VARCHAR(200) NOT NULL,  
 FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIOS) ON DELETE SET NULL
); 

CREATE TABLE EMPRESAS 
( 
 ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(100) NOT NULL UNIQUE,  
 CNPJ CHAR(14) NOT NULL UNIQUE
); 

CREATE TABLE EMPRESAS_REMEDIOS 
( 
 ID_EMPRESAS INT,  
 ID_REMEDIOS INT,  
 PRIMARY KEY (ID_EMPRESAS, ID_REMEDIOS),
 FOREIGN KEY (ID_EMPRESAS) REFERENCES EMPRESAS(ID_EMPRESA),
 FOREIGN KEY (ID_REMEDIOS) REFERENCES REMEDIOS(ID_REMEDIO)
); 