SELECT 

    R.ID_REMEDIO,
    R.NOME,
    R.BULA,
    R.TIPO,

    P.RESTRICAO,
    P.CONTRA_INDICACOES,
    P.EFEITOS,
    P.VALIDADE,
    P.CONSERVACAO,

    T.NOME AS TARJA,

    GROUP_CONCAT(DISTINCT PA.NOME SEPARATOR ', ') AS PUBLICO_ALVO,

    E.NOME AS EMPRESA,
    E.CNPJ,

    C.NOME AS CIDADE,
    C.UF,

    S.NOME AS SUBSTANCIA,
    S.TIPO AS SUBSTANCIA_TIPO

FROM REMEDIOS R

LEFT JOIN PRESCRICOES P
ON R.ID_PRESCRICAO = P.ID_PRESCRICAO

LEFT JOIN TARJAS T
ON R.ID_TARJA = T.ID_TARJA

LEFT JOIN REMEDIOS_PUBLICO_ALVO RPA
ON R.ID_REMEDIO = RPA.ID_REMEDIO

LEFT JOIN PUBLICO_ALVO PA
ON RPA.ID_PUBLICO_ALVO = PA.ID_PUBLICO_ALVO

LEFT JOIN EMPRESAS_REMEDIOS ER
ON R.ID_REMEDIO = ER.ID_REMEDIO

LEFT JOIN EMPRESAS E
ON ER.ID_EMPRESA = E.ID_EMPRESA

LEFT JOIN CIDADES C
ON E.ID_CIDADE = C.ID_CIDADE

LEFT JOIN SUBSTANCIAS_REMEDIOS SR
ON R.ID_REMEDIO = SR.ID_REMEDIO

LEFT JOIN SUBSTANCIAS S
ON SR.ID_SUBSTANCIA = S.ID_SUBSTANCIA

GROUP BY 

    R.ID_REMEDIO,
    R.NOME,
    R.BULA,
    R.TIPO,

    P.RESTRICAO,
    P.CONTRA_INDICACOES,
    P.EFEITOS,
    P.VALIDADE,
    P.CONSERVACAO,

    T.NOME,

    E.NOME,
    E.CNPJ,

    C.NOME,
    C.UF,

    S.NOME,
    S.TIPO;